export const brand = {
  name: 'CostaSol Car Rent',
  colors: {
    black:        '#0F0F10',
    graphite:     '#1B1B1D',
    ivory:        '#F5F1EA',
    gold:         '#C8A96B',
    goldHover:    '#D4B57A',
    bronze:       '#8A6A3D',
    beige:        '#D8C3A5',
    textPrimary:  '#FFFFFF',
    textSecondary:'#B8B8B8',
    textOnLight:  '#181818',
    success:      '#7A8F5A',
    warning:      '#C8A96B',
    danger:       '#E05252',
    whatsapp:     '#25D366',
    border:       'rgba(200,169,107,0.15)',
  },
  fonts: {
    display: '"Cormorant Garamond", serif',
    body:    '"Inter", sans-serif',
  },
  radii: { sm: '2px', md: '4px', lg: '6px' },
}
